### Generated by ChatGPT

import csv
from nltk.grammar import FeatureGrammar

grammar = '''
% start S

#####################
# Grammar Rules

S -> N[AGR=?a] V[AGR=?a]

# ###################
# Lexical Rules
'''

# Load verb lexical rules from CSV
with open('verb_lexicon.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        if row[0] == 'spanish':  # Skip header row
            word = row[1]
            tense = row[6]
            person = row[7]
            number = row[8]
            grammar += f"\nV[AGR=[NUM={number}, PER={person.upper()}, TENSE={tense.upper()}]] -> '{word}'"

# Load noun lexical rules from CSV
with open('noun_lexicon.csv', newline='', encoding='utf-8') as csvfile:
    reader = csv.reader(csvfile)
    for row in reader:
        if row[0] == 'spanish':  # Skip header row
            word = row[1]
            gender = row[5]
            number = row[6]
            grammar += f"\nN[AGR=[GEN={gender.upper()}, NUM={number.upper()}]] -> '{word}'"

gram = FeatureGrammar.fromstring(grammar)

print(gram)