verbs: ../../spanish/freeling-espanol/all.verbs.csv
nouns: ../../spanish/spanish-nouns/purged.nom.csv
transitivities: ../../spanish/transitivity/ancora-rae/merged-transitivities.csv
determiners: ../../spanish/spanish-determiners/determiners-sorted.csv
pronouns: ../../spanish/spanish-pronouns/pronouns.csv
adpositions: ../../guarani/adpositions/adpositions.csv
adjectives: ../../spanish/freeling-espanol/MM.adj.csv
adverbs: ../../guarani/adverbs/adverbs.csv
connectors: ../../guarani/connectors/connectors.csv
output: ../ancora/v10/feature-grammar.txt
